backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "articles"
    label: "Artykuły"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Opis", name: "excerpt", widget: "text"}
      - {label: "Typ", name: "type", widget: "select", options: ["article", "facebook_post"], default: "article"}
      - {label: "URL Facebook", name: "facebook_url", widget: "string", required: false}
      - {label: "Kategoria", name: "category", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Czas czytania", name: "read_time", widget: "string"}
      - {label: "Obraz", name: "image", widget: "image"}
      - {label: "Wyróżniony", name: "featured", widget: "boolean", default: false}
      - {label: "Treść", name: "body", widget: "markdown"}

  - name: "initiatives"
    label: "Inicjatywy"
    folder: "content/initiatives"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Opis", name: "description", widget: "text"}
      - {label: "Obraz", name: "image", widget: "image"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Status", name: "status", widget: "string", default: "Aktywna"}
      - {label: "Treść", name: "content", widget: "markdown"}

  - name: "dogs"
    label: "Psy"
    folder: "content/dogs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Imię", name: "name", widget: "string"}
      - {label: "Wiek", name: "age", widget: "string"}
      - {label: "Płeć", name: "gender", widget: "select", options: ["Samiec", "Suczka"]}
      - {label: "Rozmiar", name: "size", widget: "select", options: ["Mały", "Średni", "Duży"]}
      - {label: "Cechy szczególne", name: "special_features", widget: "list", field: {label: "Cecha", name: "feature", widget: "string"}}
      - {label: "Historia", name: "story", widget: "text"}
      - {label: "Główne zdjęcie", name: "image", widget: "image"}
      - {label: "Galeria zdjęć", name: "images", widget: "list", field: {label: "Zdjęcie", name: "image", widget: "image"}}