backend:
  name: git-gateway
  repo: justyna/pyszczynska/zpiekladodomu.pl
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "dogs"
    label: "Dogs for Adoption"
    folder: "content/dogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "name", label: "Name", widget: "string" }
      - { name: "age", label: "Age", widget: "number" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Photo", widget: "image" }
